### ISSUE TITLE
BlockLiquid其实是包括Lava的

### ISSUE THREAD

**Issue by thestarontop** [FKtzs/Nattalie#2]

**Comment by FKtzs** [comment]
但是我不会将inLava设置为public，而且我发现个问题，如果不把水也设置为空气，在hyt的海上神殿依然会被踢出

**Comment by thestarontop** [comment]
不把水设为空气会导致你一直在那发包从而发包过多，海洋神殿最优解就是在6格外发C07设空气，岩浆如果你不想死号最优解也是这个（除非你可以优化算法）

**Comment by FKtzs** [comment]
我在码字里添加了移除水，这样已经就可以很好的解决了
